[package]
name = "asgart"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "1.*"
rustc-serialize = "0.3"
palette         = "0.2.1"
log             = "0.3"
env_logger      = "0.4"
colored         = "1.*"
isatty          = "0.1"
indicatif       = "0.6"
console         = "0.5"

[dependencies.clap]
version = "2.*"
features = [ "yaml", "suggestions", "color" ]

[profile.release]
debug = true

[build-dependencies]
cmake = "0.1"