[package]
name = "asgart"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "0.1"
rustc-serialize = "0.3"
palette         = "0.2.1"
log             = "0.3"
env_logger      = "0.3"
colored         = "1.3"
isatty          = "0.1"
pbr             = {git = "https://github.com/delehef/pb.git"}

[dependencies.clap]
version = "2.10.*"
features = [ "yaml", "suggestions", "color" ]

[profile.release]
debug = true
