[package]
name = "asgart"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "0.1"
rustc-serialize = "0.3"
palette         = "0.2.1"

[dependencies.clap]
version = "2.10.*"
features = [ "yaml", "suggestions", "color" ]
