[package]
name = "asgart"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "0.1"
rustc-serialize = "0.3"

[dependencies.clap]
version = "2.10.*"
features = [ "yaml", "suggestions", "color" ]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
