[package]
name = "asgart"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "0.1"
docopt          = "0.6"
rustc-serialize = "0.3"

[features]
swap_dna = []

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
